import type { Metadata } from 'next'
import { Montserrat } from 'next/font/google'
import { Toaster } from '@/components/ui/sonner'
import { Navbar } from '@/components/Navbar/Navbar'
import { AuthProvider } from '@/contexts/AuthProvider'
import { getServerSession, serverClient } from '@/lib/serverClient'
import './globals.css'
import { User } from '@supabase/supabase-js'
import { cookies } from 'next/headers'

const montserrat = Montserrat({
  variable: '--font-mont',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const client = await serverClient()
  const {
    data: { user },
  } = (await client?.auth.getUser()) as { data: { user: User } }

  return (
    <html lang="en">
      <AuthProvider initialUser={user}>
        <body className={`${montserrat.variable} antialiased bg-black`}>
          <Navbar />
          <main>{children}</main>
          <Toaster duration={5000} position="top-center" />
        </body>
      </AuthProvider>
    </html>
  )
}
